name: patternbayes-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - numpy>=1.21
  - scipy>=1.7
  - pytorch>=1.12 # Match pyproject.toml, or specify cpuonly/cuda version if desired
  - cpuonly # Example: add this if you only need CPU support for pytorch

  # Development dependencies
  - pytest>=7.0
  - mypy>=0.9
  - ruff>=0.1
  - black>=23.0
  - pytest-cov>=4.0
  - coverage>=6.0

  # Documentation dependencies
  - sphinx>=5.0
  - sphinx-rtd-theme>=1.0
  - nbsphinx>=0.8
  - matplotlib

  # Pip dependencies (if any conda package is not available)
  # - pip:
  #   - some-pip-package 